/**
 * Default registration rules. Each one cites the clause it implements so a
 * violation can open the exact page of the regulation in the source viewer
 * (document titles match the knowledge base). Page numbers are PDF pages.
 *
 * Seeded insert-only at startup: once a rule exists, the registrar's edits win.
 */
import type { RuleDefinition, RuleSource } from '../domain/rule-engine/types';

export type RuleSeed = RuleDefinition & { description: { mn: string; en: string } | null };

const ORDER_199 = 'ШУТИС тушаал №199 (2025-06-06)';
const HANDBOOK = 'Шинэ оюутанд зориулсан гарын авлага 2022';

const order199 = (clause: string, page: number): RuleSource => ({ docTitle: ORDER_199, clause, page });

/**
 * Rules that used to be defaults and are removed from existing databases at
 * startup. The app plans timetables; it neither reserves seats nor handles
 * payment, so SEAT_AVAILABLE and TUITION_PAID no longer apply.
 */
export const RETIRED_RULES = ['SEAT_AVAILABLE', 'TUITION_PAID'];

export const DEFAULT_RULES: RuleSeed[] = [
  // ------------------------------------------------ Хичээл сонголт 1 ----
  {
    code: 'OFFERED_THIS_TERM',
    phase: 'selection',
    scope: 'course',
    severity: 'error',
    enabled: true,
    priority: 10,
    title: { mn: 'Энэ улиралд нээгдсэн хичээл', en: 'Offered this term' },
    description: null,
    when: null,
    condition: { fact: 'course.offered', op: 'eq', value: true },
    params: {},
    message: {
      mn: '{course.code} «{course.name}» хичээл энэ улиралд нээгдээгүй байна.',
      en: '{course.code} “{course.name}” is not offered this term.',
    },
    source: null,
  },
  {
    code: 'ALREADY_PASSED',
    phase: 'selection',
    scope: 'course',
    severity: 'error',
    enabled: true,
    priority: 20,
    title: { mn: 'Тэнцсэн хичээлийг давтан судлах', en: 'Retaking a passed course' },
    description: {
      mn: 'Сургуулийн тохируулж болох бодлого: зөвхөн бага дүнтэй хичээлийг дүнгээ ахиулахаар давтан сонгоно.',
      en: 'Configurable school policy: only low-graded courses may be retaken to improve the grade.',
    },
    when: { fact: 'course.passed', op: 'eq', value: true },
    condition: { fact: 'course.bestGradePoint', op: 'lt', value: { param: 'retakeBelow' } },
    params: { retakeBelow: 2.0 },
    message: {
      mn: '{course.code} хичээлийг {course.bestLetter} үнэлгээтэй тэнцсэн байна. Үнэлгээний оноо {params.retakeBelow}-аас бага хичээлийг л дүнгээ ахиулахаар давтан сонгоно.',
      en: 'You already passed {course.code} with {course.bestLetter}. Only courses below {params.retakeBelow} grade points can be retaken to improve the grade.',
    },
    source: null,
  },
  {
    code: 'PREREQUISITES',
    phase: 'selection',
    scope: 'course',
    severity: 'error',
    enabled: true,
    priority: 30,
    title: { mn: 'Өмнөх холбоо хичээл', en: 'Prerequisites' },
    description: null,
    when: null,
    condition: { fact: 'course.prereqStatus', op: 'ne', value: 'missing' },
    params: {},
    message: {
      mn: '{course.code} хичээлийг судлах эрх өмнөх холбоо хичээлээ үнэлүүлсний дараа үүснэ. Тэнцээгүй: {course.missingPrerequisites}.',
      en: '{course.code} can be taken only after its prerequisites are passed. Missing: {course.missingPrerequisites}.',
    },
    source: order199('8.6', 12),
  },
  {
    code: 'PREREQ_IN_PROGRESS',
    phase: 'selection',
    scope: 'course',
    severity: 'warning',
    enabled: true,
    priority: 31,
    title: { mn: 'Өмнөх холбоо хичээл судлагдаж байна', en: 'Prerequisite in progress' },
    description: null,
    when: null,
    condition: { fact: 'course.prereqStatus', op: 'ne', value: 'pending' },
    params: {},
    message: {
      mn: '{course.code}-ийн өмнөх холбоо хичээл {course.pendingPrerequisites}-г та одоо судалж байна. Тэнцээгүй тохиолдолд энэ сонголт цуцлагдана.',
      en: 'You are still taking {course.pendingPrerequisites}, the prerequisite of {course.code}. If you do not pass it, this selection will be cancelled.',
    },
    source: order199('8.6', 12),
  },
  {
    code: 'ALREADY_TAKING',
    phase: 'selection',
    scope: 'course',
    severity: 'warning',
    enabled: true,
    priority: 25,
    title: { mn: 'Одоо судалж буй хичээл', en: 'Course you are taking now' },
    description: null,
    when: null,
    condition: { fact: 'course.inProgress', op: 'eq', value: false },
    params: {},
    message: {
      mn: 'Та {course.code} хичээлийг энэ улиралд судалж байна. Тэнцэхгүй гэж үзвэл л дахин сонгоно уу.',
      en: 'You are taking {course.code} this term. Select it again only if you expect to retake it.',
    },
    source: null,
  },
  {
    code: 'IN_CURRICULUM',
    phase: 'selection',
    scope: 'course',
    severity: 'warning',
    enabled: true,
    priority: 40,
    title: { mn: 'Сургалтын төлөвлөгөөнд хамаарах', en: 'Counts toward your curriculum' },
    description: null,
    when: null,
    condition: { fact: 'course.inCurriculum', op: 'eq', value: true },
    params: {},
    message: {
      mn: '{course.code} таны хөтөлбөрийн сургалтын төлөвлөгөөнд ороогүй тул зөвхөн нээлттэй сонгон кредитэд тооцогдоно.',
      en: '{course.code} is not in your program’s curriculum, so it counts only as an open elective.',
    },
    source: order199('8.4', 11),
  },
  {
    code: 'MAX_CREDITS_MAIN',
    phase: 'selection',
    scope: 'plan',
    severity: 'error',
    enabled: true,
    priority: 50,
    title: { mn: 'Үндсэн улирлын кредитийн дээд хэмжээ', en: 'Credit limit — main semester' },
    description: null,
    when: { all: [{ fact: 'term.isMain', op: 'eq', value: true }, { fact: 'student.isDualProgram', op: 'eq', value: false }] },
    condition: { fact: 'plan.loadCredits', op: 'lte', value: { param: 'max' } },
    params: { max: 21 },
    message: {
      mn: 'Үндсэн улиралд судлах кредитийн дээд хэмжээ {params.max}. Таны сонголт {plan.loadCredits} кредит (дадлага тооцохгүй).',
      en: 'At most {params.max} credits per main semester. Your selection is {plan.loadCredits} credits (internships excluded).',
    },
    source: order199('9.6', 15),
  },
  {
    code: 'MAX_CREDITS_DUAL',
    phase: 'selection',
    scope: 'plan',
    severity: 'error',
    enabled: true,
    priority: 51,
    title: { mn: 'Хавсарга, хос хөтөлбөрийн кредитийн дээд хэмжээ', en: 'Credit limit — minor / double program' },
    description: null,
    when: { all: [{ fact: 'term.isMain', op: 'eq', value: true }, { fact: 'student.isDualProgram', op: 'eq', value: true }] },
    condition: { fact: 'plan.loadCredits', op: 'lte', value: { param: 'max' } },
    params: { max: 30 },
    message: {
      mn: 'Хавсарга, хос, хамтарсан хөтөлбөрөөр суралцаж буй оюутан нэг улиралд {params.max} хүртэл кредит сонгоно. Таны сонголт {plan.loadCredits}.',
      en: 'Students in a minor, double or joint program may take up to {params.max} credits. Your selection is {plan.loadCredits}.',
    },
    source: order199('9.7', 15),
  },
  {
    code: 'MAX_CREDITS_WINTER',
    phase: 'selection',
    scope: 'plan',
    severity: 'error',
    enabled: true,
    priority: 52,
    title: { mn: 'Өвлийн улирлын кредитийн дээд хэмжээ', en: 'Credit limit — winter term' },
    description: null,
    when: { fact: 'term.type', op: 'eq', value: 'winter' },
    condition: { fact: 'plan.loadCredits', op: 'lte', value: { param: 'max' } },
    params: { max: 3 },
    message: {
      mn: 'Өвлийн улиралд судлах кредитийн дээд хэмжээ {params.max}. Таны сонголт {plan.loadCredits}.',
      en: 'At most {params.max} credits in the winter term. Your selection is {plan.loadCredits}.',
    },
    source: order199('9.6', 15),
  },
  {
    code: 'MAX_CREDITS_SUMMER',
    phase: 'selection',
    scope: 'plan',
    severity: 'error',
    enabled: true,
    priority: 53,
    title: { mn: 'Зуны улирлын кредитийн дээд хэмжээ', en: 'Credit limit — summer term' },
    description: null,
    when: { fact: 'term.type', op: 'eq', value: 'summer' },
    condition: { fact: 'plan.loadCredits', op: 'lte', value: { param: 'max' } },
    params: { max: 6 },
    message: {
      mn: 'Зуны улиралд {params.max}-аас илүүгүй кредит судална. Таны сонголт {plan.loadCredits}.',
      en: 'At most {params.max} credits in the summer term. Your selection is {plan.loadCredits}.',
    },
    source: order199('9.6', 15),
  },
  {
    code: 'RECOMMENDED_LOAD',
    phase: 'selection',
    scope: 'plan',
    severity: 'warning',
    enabled: true,
    priority: 60,
    title: { mn: 'Зөвлөмжит ачаалал', en: 'Recommended load' },
    description: null,
    when: { all: [{ fact: 'term.isMain', op: 'eq', value: true }, { fact: 'plan.courseCount', op: 'gt', value: 0 }] },
    condition: { fact: 'plan.loadCredits', op: 'gte', value: { param: 'min' } },
    params: { min: 12 },
    message: {
      mn: 'Үндсэн улиралд дунджаар 15 кредит судлах нь зохимжтой. Таны сонголт {plan.loadCredits} кредит буюу {params.min}-аас бага байна.',
      en: 'About 15 credits per main semester is recommended. Your selection is {plan.loadCredits} credits, below {params.min}.',
    },
    source: order199('9.6', 15),
  },
  {
    code: 'ACADEMIC_WARNING_LOAD',
    phase: 'selection',
    scope: 'plan',
    severity: 'warning',
    enabled: true,
    priority: 70,
    title: { mn: 'Анхааруулгын хуудсанд бичигдсэн үеийн ачаалал', en: 'Load while on academic warning' },
    description: null,
    when: { fact: 'student.onWarning', op: 'eq', value: true },
    condition: { fact: 'plan.loadCredits', op: 'lte', value: { param: 'max' } },
    params: { max: 15 },
    message: {
      mn: 'Өмнөх улирлын голч дүн {student.lastTermGpa} (≤ 1.00) тул та анхааруулгын хуудсанд бичигдсэн; 3 удаа бичигдвэл сургуулиас хасагдана. {params.max}-аас ихгүй кредит сонгохыг зөвлөж байна.',
      en: 'Your last semester GPA was {student.lastTermGpa} (≤ 1.00), so you are on the academic warning list; a third time means dismissal. Consider at most {params.max} credits.',
    },
    source: order199('10.21', 18),
  },

  // ------------------------------------------------ Хичээл сонголт 2 ----
  {
    code: 'COURSE_SELECTED',
    phase: 'schedule',
    scope: 'section',
    severity: 'error',
    enabled: true,
    priority: 20,
    title: { mn: 'Хичээл сонголт 1-ийн хичээл', en: 'Course from Course Selection 1' },
    description: null,
    when: null,
    condition: { fact: 'section.courseSelected', op: 'eq', value: true },
    params: {},
    message: {
      mn: '{section.courseCode} хичээлийг Хичээл сонголт 1-д сонгоогүй тул цаг, багш сонгох боломжгүй.',
      en: '{section.courseCode} was not chosen in Course Selection 1, so its class times cannot be picked.',
    },
    source: { docTitle: HANDBOOK, clause: null, page: 34 },
  },
  {
    code: 'TIME_CONFLICT',
    phase: 'schedule',
    scope: 'section',
    severity: 'error',
    enabled: true,
    priority: 40,
    title: { mn: 'Цагийн давхцал', en: 'Time conflict' },
    description: null,
    when: null,
    condition: { fact: 'section.conflictCount', op: 'eq', value: 0 },
    params: {},
    message: {
      mn: '{section.label} нь {section.conflictsWith}-тай цаг давхцаж байна.',
      en: '{section.label} clashes with {section.conflictsWith}.',
    },
    source: null,
  },
  {
    code: 'COMPONENTS_COMPLETE',
    phase: 'schedule',
    scope: 'course',
    severity: 'warning',
    enabled: true,
    priority: 50,
    title: { mn: 'Хичээлийн хэлбэрүүд', en: 'Class components' },
    description: null,
    when: null,
    condition: { fact: 'course.missingComponents', op: 'isEmpty' },
    params: {},
    message: {
      mn: '{course.code}: {course.missingComponentsMn} цагаа сонгоогүй байна.',
      en: '{course.code}: no {course.missingComponentsEn} chosen yet.',
    },
    source: order199('8.8', 12),
  },
  {
    code: 'DAILY_LOAD',
    phase: 'schedule',
    scope: 'plan',
    severity: 'warning',
    enabled: true,
    priority: 60,
    title: { mn: 'Өдрийн ачаалал', en: 'Daily load' },
    description: {
      mn: 'Сургуулийн нэмэлт зөвлөмж — бүртгэлийн алба тохируулж, унтрааж болно.',
      en: 'An extra school recommendation — the registrar can tune or switch it off.',
    },
    when: null,
    condition: { fact: 'plan.maxMeetingsPerDay', op: 'lte', value: { param: 'max' } },
    params: { max: 4 },
    message: {
      mn: 'Нэг өдөр {plan.maxMeetingsPerDay} цаг хичээлтэй байна. Өдөрт {params.max}-аас ихгүй цаг төлөвлөхийг зөвлөж байна.',
      en: 'One day has {plan.maxMeetingsPerDay} classes; at most {params.max} per day is recommended.',
    },
    source: null,
  },
];
